project_id = "dscndbpqvhvylukvcgpq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[functions.gemini-chat]
verify_jwt = true

[functions.plaid-link-exchange]
verify_jwt = true

[functions.plaid-sync]
verify_jwt = true

[functions.share-get-budget-by-token]
verify_jwt = false

[functions.send-budget-email]
verify_jwt = true

[functions.send-budget-sms]
verify_jwt = true