require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# Modern CocoaPods configuration
install! 'cocoapods', :deterministic_uuids => false

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'

end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
  
  # Fix for Xcode warning about script phase outputs
  installer.pods_project.targets.each do |target|
    target.build_phases.each do |phase|
      if phase.is_a?(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
        if phase.name == '[CP] Embed Pods Frameworks'
          # Add output paths to prevent the warning
          phase.output_paths = [
            "$(TARGET_BUILD_DIR)/$(FRAMEWORKS_FOLDER_PATH)/Capacitor.framework",
            "$(TARGET_BUILD_DIR)/$(FRAMEWORKS_FOLDER_PATH)/Cordova.framework"
          ]
        end
      end
    end
  end
end
